INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('CHICKEN CROWN', 1, 10.50);
INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('CHICKEN NUGGETS', 6, 2.5);
INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('CHICKEN TENDERS', 2, 1.25);
INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('CHICKEN NOODLES', 3, 0.75);
INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('KIMCHI RAMYUM', 9, .95);
INSERT INTO FOOD (ITEM_NAME, QUANTITY, PRICE) VALUES ('SHIN RAMYUM', 3, 0.95);