DROP TABLE IF EXISTS FOOD;

CREATE TABLE FOOD(
ID SMALLINT NOT NULL AUTO_INCREMENT,
ITEM_NAME VARCHAR(50) NOT NULL DEFAULT '',
QUANTITY INT NOT NULL DEFAULT 1,
PRICE FLOAT NOT NULL DEFAULT 0,
PRIMARY KEY (ID));